### ISSUE TITLE
List events participants alphabetically

### ISSUE THREAD

**Issue by k-boy** [webaccess/com.webaccessglobal.module.civimobile#43]
I will like the have the names of event participants listed alphabetically on the event check-in screen, how can i modify the civimobile extension (civimobile.participant_checkin.html) to list names alphabetically?

**Comment by kurund** [comment]
@k-boy currently you cannot modify it via UI. Yes you can modify civimobile.participant_checkin.html and add 'options param to 

CRM.api('Participant','get', ......

'options' => array('sort' => "sort_name"),

**Comment by k-boy** [comment]
thank you for your reply Kurund! Please could you tell me how to modify the api call from line 35 ? I am still struggling with the api calls:

 CRM.api('Participant','get',
        {'version' :'3', 'sort_name': q, 'event_id': eventId, 'participant_status_id': {1:1,2:2,5:5},
          'return' : 'display_name,participant_status_id', 'rowCount' : 500 },
        {
          success:function (data){
            if (data.count == 0) {
              cmd = null;
            }
            else {

**Comment by k-boy** [comment]
Hi Kurund, I have not been able to get this to work. Can you help?

Thank you in advance.

**Comment by k-boy** [comment]
Hi Kurund and sorry to bother you again 

your above solution works , modifying line 35 CRM.api('Participant','get',   to CRM.api('Participant','get', {"sequential": 1,"options": {"sort":"display_name"} works just fine for CiviCRM version 4.3

When i do the same changes on line 35 of civimobile.participant_checkin.html, i get page not found sites/all/modules/civicrm//bower_components/lodash-compat/lodash.min.js

Is it possible for you to tell me how to modify the sorting for this version of civimobile downloaded here on Github?

Many thanks in advance!

**Comment by kurund** [comment]
@k-boy We have done some work to upgrade civimobile to 4.6, but not yet released. Outstanding issues is survey functionality

**Comment by kurund** [comment]
We have pushed 4.7 compatible release

**Comment by kurund** [comment]
this is also duplicate of https://github.com/webaccess/com.webaccessglobal.module.civimobile/issues/36
