### ISSUE TITLE
What is status of civimobile for CiviCRM 4.6?

### ISSUE THREAD

**Issue by JoeMurray** [webaccess/com.webaccessglobal.module.civimobile#44]
There is a commit to info.xml indicating support exists for 4.6, but there is no release. Is this in production anywhere with 4.6? Any plans on releasing for 4.6? Any specific issues that are blockers for a 4.6 release? I'm trying to create a budget for an upgrade to 4.6 for a client that uses civimobile.

**Comment by kurund** [comment]
Survey functionality is broken due to API changes.

**Comment by kurund** [comment]
We have pushed 4.7 compatible release

**Comment by JoeMurray** [comment]
Thanks for the update. Very happy there's a release.
